[versions]
androidx-test-core = "1.6.1"
androidx-test-runner = "1.6.2"

gradle-android = "8.2.2"
gradle-kmp-configuration = "0.2.2"
gradle-kotlin = "1.9.24"

[libraries]
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "gradle-kmp-configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "gradle-kotlin" }

[plugins]
android-app = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.library", version.ref = "gradle-android" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
